blockExoticSubdeps: true
catalog:
  '@types/jest': ^30.0.0
  '@types/node': ^24.13.3
  jest: ^30.5.1
  ts-jest: ^29.4.12
  tsdown: ^0.22.14
  typescript: ^5.9.3
catalogMode: strict
minimumReleaseAge: 20160 # 30 days
minimumReleaseAgeExclude:
  - '@jsnw/*'
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 40320 # 60 days
